<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>403 Forbidden</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #E57368;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 300;
                margin-bottom: 0;
            }

            .descriptor
            {
                margin-top: 25px;
            }
        </style>
    </head>
    <body>
        <h1>403<br>Forbidden</h1>
        <div class="descriptor">You are probably looking at the wrong place</div>
    </body>
</html>
